import type { Metadata } from "next";
import "./globals.css";
import { ThemeProvider } from "@/components/theme-provider";
import { ToastContainer } from "react-toastify";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  icons: {
    icon: "/images/favicon.svg", // or '/favicon.png' or '/icon.svg'
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <ToastContainer
            position="top-center"
            autoClose={3000}
            hideProgressBar={true}
            newestOnTop={true}
            closeOnClick={true}
            closeButton={false}
            pauseOnFocusLoss={true}
            draggable={"touch"}
            draggableDirection="y"
            pauseOnHover={true}
            draggablePercent={100}
            theme="colored"
            toastClassName="mobile-style-toast"
          />
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
